In [1]:
#eliminar elementos en series y dataframes

In [2]:
import pandas as pd
import numpy as np

In [3]:
np.arange(4)
serie = pd.Series(np.arange(4), index=['a','b','c','d'])
serie

a    0
b    1
c    2
d    3
dtype: int32

In [5]:
serie.drop('c') #borrar el indice c

a    0
b    1
d    3
dtype: int32

In [6]:
#pero no se borra de la serie
serie

a    0
b    1
c    2
d    3
dtype: int32

In [8]:
#borrar de un dataframe
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
lista = np.arange(9).reshape(3,3)

In [10]:
indices = ['a','b','c']
columnas = ['c1','c2','c3']
dataframe = pd.DataFrame(lista,index=indices,columns=columnas)

In [11]:
dataframe

c1  c2  c3
a   0   1   2
b   3   4   5
c   6   7   8

In [12]:
dataframe.drop('b')

c1  c2  c3
a   0   1   2
c   6   7   8

In [13]:
dataframe

c1  c2  c3
a   0   1   2
b   3   4   5
c   6   7   8

In [14]:
dataframe.drop('c3',axis=1)

c1  c2
a   0   1
b   3   4
c   6   7

In [15]:
#para actualizar el dataframe y hacer cambios permanentes
dataframe = dataframe.drop('c3',axis=1)

In [16]:
dataframe

c1  c2
a   0   1
b   3   4
c   6   7

In [27]:
#Seleccionar datos en las series
lista = np.arange(3)
indices = ['i1','i2','i3']
serie = pd.Series(lista,index=indices)
serie

i1    0
i2    1
i3    2
dtype: int32

In [28]:
serie = serie * 2
serie

i1    0
i2    2
i3    4
dtype: int32

In [29]:
#acceder a los elementos
serie['i2']

2

In [30]:
serie[1]

2

In [31]:
serie[0:3]

i1    0
i2    2
i3    4
dtype: int32

In [32]:
serie['i1':'i3']

i1    0
i2    2
i3    4
dtype: int32

In [33]:
serie[serie>3]

i3    4
dtype: int32

In [34]:
#podemos cambiar un valor
serie[serie>3] = 6

In [35]:
serie

i1    0
i2    2
i3    6
dtype: int32

In [36]:
#seleccionar elementos en el dataframe--------------

In [38]:
lista = np.arange(25).reshape(5,5)
indices = ['i1','i2','i3','i4','i5']
columnas = ['c1','c2','c3','c4','c5']
dataframe = pd.DataFrame(lista,index=indices,columns=columnas)
dataframe

c1  c2  c3  c4  c5
i1   0   1   2   3   4
i2   5   6   7   8   9
i3  10  11  12  13  14
i4  15  16  17  18  19
i5  20  21  22  23  24

In [40]:
dataframe['c2'] #vemos columa 2

i1     1
i2     6
i3    11
i4    16
i5    21
Name: c2, dtype: int32

In [41]:
dataframe['c2']['i2']

6

In [42]:
#seleccionar varias columnas
dataframe[['c3','c4']]

c3  c4
i1   2   3
i2   7   8
i3  12  13
i4  17  18
i5  22  23

In [46]:
#seleccionar por rangos
lista_indices= ['c2','c3','c5']
dataframe[lista_indices]

c2  c3  c5
i1   1   2   4
i2   6   7   9
i3  11  12  14
i4  16  17  19
i5  21  22  24

In [47]:
#usando condiciones
dataframe[dataframe['c2']>15]

c1  c2  c3  c4  c5
i4  15  16  17  18  19
i5  20  21  22  23  24

In [49]:
#Ver que condiciones se cumplen dentro
dataframe > 20 

c1     c2     c3     c4     c5
i1  False  False  False  False  False
i2  False  False  False  False  False
i3  False  False  False  False  False
i4  False  False  False  False  False
i5  False   True   True   True   True

In [51]:
#busqueda por indice
dataframe.loc['i3']

c1    10
c2    11
c3    12
c4    13
c5    14
Name: i3, dtype: int32

In [52]:
dataframe.loc['i3']['c4']

13

In [54]:
#operaciones sobre series o dataframes

In [55]:
serie1 = pd.Series([0,1,2],index=['a','b','c'])
serie1

a    0
b    1
c    2
dtype: int64

In [56]:
serie2 = pd.Series([3,4,5,6],index=['a','b','c','d'])
serie2

a    3
b    4
c    5
d    6
dtype: int64

In [58]:
serie1 + serie2 #las filas sin valores da NaN

a    3.0
b    5.0
c    7.0
d    NaN
dtype: float64

In [59]:
#vemos ahora los dataframes
valores = np.arange(4).reshape(2,2)
valores

array([[0, 1],
       [2, 3]])

In [60]:
indices = list('ab')
indices

['a', 'b']

In [61]:
columnas = list('12')
columnas

['1', '2']

In [62]:
dataframe = pd.DataFrame(valores,index=indices,columns=columnas)

In [63]:
dataframe

1  2
a  0  1
b  2  3

In [64]:
valores2 = np.arange(9).reshape(3,3)
indices2 = list('abc')
columnas2 = list('123')
dataframe2 = pd.DataFrame(valores2,index=indices2,columns=columnas2)
dataframe2

1  2  3
a  0  1  2
b  3  4  5
c  6  7  8

In [65]:
dataframe+dataframe2

1    2   3
a  0.0  2.0 NaN
b  5.0  7.0 NaN
c  NaN  NaN NaN

In [66]:
dataframe2+dataframe

1    2   3
a  0.0  2.0 NaN
b  5.0  7.0 NaN
c  NaN  NaN NaN

In [67]:
dataframe3 = dataframe+dataframe2

In [68]:
dataframe3[dataframe3>=0]

1    2   3
a  0.0  2.0 NaN
b  5.0  7.0 NaN
c  NaN  NaN NaN

In [69]:
dataframe.add(dataframe2,fill_value=0)

1    2    3
a  0.0  2.0  2.0
b  5.0  7.0  5.0
c  6.0  7.0  8.0

In [70]:
#Ordenar y clasificar series

In [71]:
valores = range(4)
indices = list('CBAD')
serie = pd.Series(valores,index=indices)

In [72]:
serie

C    0
B    1
A    2
D    3
dtype: int64

In [74]:
serie.sort_index() #ordena por indice

A    2
B    1
C    0
D    3
dtype: int64

In [75]:
serie.sort_values() #ordena por valores

C    0
B    1
A    2
D    3
dtype: int64

In [76]:
serie.rank() #ranking de los indices en base a sus valores

C    1.0
B    2.0
A    3.0
D    4.0
dtype: float64

In [77]:
serie2 = pd.Series(np.random.randn(10))

In [78]:
serie2.rank()

0     8.0
1     5.0
2     9.0
3     2.0
4     7.0
5     4.0
6     1.0
7     6.0
8     3.0
9    10.0
dtype: float64

In [79]:
serie2.sort_values()

6   -0.562929
3   -0.449437
8   -0.358493
5   -0.290888
1   -0.243551
7    0.109963
4    0.121872
0    0.131029
2    1.035030
9    1.817994
dtype: float64

In [80]:
serie2.sort_index()

0    0.131029
1   -0.243551
2    1.035030
3   -0.449437
4    0.121872
5   -0.290888
6   -0.562929
7    0.109963
8   -0.358493
9    1.817994
dtype: float64

In [81]:
#estadisticas en dataframe

In [83]:
array = np.array([[1,8,3],[5,6,7]])

In [84]:
dataframe = pd.DataFrame(array,index=['a','b'],columns=list('123'))

In [85]:
dataframe

1  2  3
a  1  8  3
b  5  6  7

In [87]:
dataframe.sum() #suma por columnas

1     6
2    14
3    10
dtype: int64

In [89]:
dataframe.sum(axis=1) #suma por filas

a    12
b    18
dtype: int64

In [90]:
#minimo
dataframe.min()

1    1
2    6
3    3
dtype: int32

In [91]:
dataframe.max(axis=1)

a    8
b    7
dtype: int32

In [92]:
#indice del valor min
dataframe.idxmin()

1    a
2    b
3    a
dtype: object

In [93]:
#Valores estadisticos
dataframe.describe()

1         2         3
count  2.000000  2.000000  2.000000
mean   3.000000  7.000000  5.000000
std    2.828427  1.414214  2.828427
min    1.000000  6.000000  3.000000
25%    2.000000  6.500000  4.000000
50%    3.000000  7.000000  5.000000
75%    4.000000  7.500000  6.000000
max    5.000000  8.000000  7.000000

In [94]:
#VALORES NULOS NaN

In [95]:
lista = ['1','2',np.nan,4]

In [96]:
serie = pd.Series(lista,index=list('abcd'))
serie

a      1
b      2
c    NaN
d      4
dtype: object

In [97]:
serie.isnull()

a    False
b    False
c     True
d    False
dtype: bool

In [99]:
#borrar nulos , no desaparece de original
serie.dropna()

a    1
b    2
d    4
dtype: object

In [100]:
#Ahora con DataFrame
lista = [[1,2,3],[4,np.nan,5],[6,7,np.nan]]
lista

[[1, 2, 3], [4, nan, 5], [6, 7, nan]]

In [102]:
indices = list('123')

In [103]:
columnas = list('abc')

In [104]:
dataframe = pd.DataFrame(lista,index=indices,columns=columnas)

In [105]:
dataframe

a    b    c
1  1  2.0  3.0
2  4  NaN  5.0
3  6  7.0  NaN

In [106]:
dataframe.isnull()

a      b      c
1  False  False  False
2  False   True  False
3  False  False   True

In [108]:
dataframe.dropna() #elimina filas que contienen NaN

a    b    c
1  1  2.0  3.0

In [109]:
#rellenar los nulos con ceros
dataframe.fillna(0)

a    b    c
1  1  2.0  3.0
2  4  0.0  5.0
3  6  7.0  0.0

In [110]:
#Jerarquia de indices

In [111]:
valores = np.random.rand(6)
valores

array([0.32774693, 0.14647045, 0.935405  , 0.93114574, 0.9526074 ,
       0.86554172])

In [112]:
indices = [[1,1,1,2,2,2],['a','b','c','a','b','c']]

In [113]:
series = pd.Series(valores,index=indices)

In [114]:
series

1  a    0.327747
   b    0.146470
   c    0.935405
2  a    0.931146
   b    0.952607
   c    0.865542
dtype: float64

In [117]:
series[1]

a    0.327747
b    0.146470
c    0.935405
dtype: float64

In [118]:
series[1]['b']

0.14647045108555556

In [119]:
#generamos un dataframe a partir de los doble indices

In [120]:
dataframe = series.unstack()

In [121]:
dataframe

a         b         c
1  0.327747  0.146470  0.935405
2  0.931146  0.952607  0.865542

In [122]:
#ahora el proceso inverso

In [123]:
val = np.arange(16).reshape(4,4)
val

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [124]:
ind = list('1234')
ind

['1', '2', '3', '4']

In [ ]:
col = list('abcd')
col