In [1]:
#Agrupar datos en categorias

In [3]:
import pandas as pd
import numpy as np

In [6]:
precios = [34,45,65,3,55,23,21,14,99]
rango = [0,10,20,30,40,50,60,70,80,90,100]

In [7]:
precios_con_rango = pd.cut(precios, rango) #agrupa o corta en el rango
precios_con_rango

[(30, 40], (40, 50], (60, 70], (0, 10], (50, 60], (20, 30], (20, 30], (10, 20], (90, 100]]
Categories (10, interval[int64]): [(0, 10] < (10, 20] < (20, 30] < (30, 40] ... (60, 70] < (70, 80] < (80, 90] < (90, 100]]

In [9]:
pd.value_counts(precios_con_rango) #contar cuantos hay en cada categoria

(20, 30]     2
(90, 100]    1
(60, 70]     1
(50, 60]     1
(40, 50]     1
(30, 40]     1
(10, 20]     1
(0, 10]      1
(80, 90]     0
(70, 80]     0
dtype: int64

In [10]:
#Filtrar datos en Dataframes

In [11]:
valores = np.random.rand(10,3)
valores

array([[0.40819843, 0.39128256, 0.08987996],
       [0.88334558, 0.52172995, 0.52242755],
       [0.06468742, 0.29732537, 0.94307317],
       [0.48094692, 0.16417153, 0.19622961],
       [0.11190657, 0.30252614, 0.24582117],
       [0.76771441, 0.78617842, 0.52209247],
       [0.17041689, 0.9751    , 0.00563026],
       [0.50330859, 0.93880792, 0.66427498],
       [0.49845214, 0.51302875, 0.25777396],
       [0.03666784, 0.8303772 , 0.97187247]])

In [12]:
dataframe = pd.DataFrame(valores)
dataframe

0         1         2
0  0.408198  0.391283  0.089880
1  0.883346  0.521730  0.522428
2  0.064687  0.297325  0.943073
3  0.480947  0.164172  0.196230
4  0.111907  0.302526  0.245821
5  0.767714  0.786178  0.522092
6  0.170417  0.975100  0.005630
7  0.503309  0.938808  0.664275
8  0.498452  0.513029  0.257774
9  0.036668  0.830377  0.971872

In [13]:
#seleccionar columna cero

In [14]:
col_0 = dataframe[0]
col_0

0    0.408198
1    0.883346
2    0.064687
3    0.480947
4    0.111907
5    0.767714
6    0.170417
7    0.503309
8    0.498452
9    0.036668
Name: 0, dtype: float64

In [15]:
col_0[col_0 > 0.40]

0    0.408198
1    0.883346
3    0.480947
5    0.767714
7    0.503309
8    0.498452
Name: 0, dtype: float64

In [16]:
dataframe[dataframe > 0.40]

0         1         2
0  0.408198       NaN       NaN
1  0.883346  0.521730  0.522428
2       NaN       NaN  0.943073
3  0.480947       NaN       NaN
4       NaN       NaN       NaN
5  0.767714  0.786178  0.522092
6       NaN  0.975100       NaN
7  0.503309  0.938808  0.664275
8  0.498452  0.513029       NaN
9       NaN  0.830377  0.971872

In [17]:
#Combinar elementos de dataframes

In [19]:
lista = np.arange(25).reshape(5,5)
lista

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [20]:
dataframe = pd.DataFrame(lista)

In [21]:
dataframe

0   1   2   3   4
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19
4  20  21  22  23  24

In [22]:
combinacion_aleatoria = np.random.permutation(5)
combinacion_aleatoria

array([4, 1, 2, 0, 3])

In [23]:
#ordenamos segun ese array

In [25]:
dataframe.take(combinacion_aleatoria)

0   1   2   3   4
4  20  21  22  23  24
1   5   6   7   8   9
2  10  11  12  13  14
0   0   1   2   3   4
3  15  16  17  18  19