In [1]:
#concatenacion de arrays, series y dataframes

In [3]:
import pandas as pd
import numpy as np

In [4]:
array1 = np.arange(9).reshape(3,3)
array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.concatenate([array1,array1])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [7]:
#concatenando hacia la derecha
np.concatenate([array1,array1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [8]:
#Concatenar series
serie1 = pd.Series([1,2,3],index=['a','b','c'])
serie2 = pd.Series([4,5,6],index=['d','e','f'])

In [9]:
pd.concat([serie1,serie2])

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [10]:
#agrego claves extras
pd.concat([serie1,serie2],keys=['serie1','serie2'])

serie1  a    1
        b    2
        c    3
serie2  d    4
        e    5
        f    6
dtype: int64

In [11]:
#CONCATENAR DATAFRAMES

In [12]:
dt1= pd.DataFrame(np.random.rand(3,3),columns=list('abc'))
dt1

a         b         c
0  0.196650  0.883851  0.171014
1  0.449483  0.233378  0.383888
2  0.426626  0.278839  0.440789

In [13]:
dt2 = pd.DataFrame(np.random.rand(2,3),columns=list('abc'))
dt2

a         b         c
0  0.556190  0.184927  0.430684
1  0.369736  0.942904  0.515082

In [14]:
dt3 = pd.concat([dt1,dt2])
dt3

a         b         c
0  0.196650  0.883851  0.171014
1  0.449483  0.233378  0.383888
2  0.426626  0.278839  0.440789
0  0.556190  0.184927  0.430684
1  0.369736  0.942904  0.515082

In [15]:
#organizando los indices
dt3 = pd.concat([dt1,dt2],ignore_index=True)
dt3

a         b         c
0  0.196650  0.883851  0.171014
1  0.449483  0.233378  0.383888
2  0.426626  0.278839  0.440789
3  0.556190  0.184927  0.430684
4  0.369736  0.942904  0.515082

In [16]:
#COMBINAR SERIES y DATAFRAMES

In [17]:
serie1 = pd.Series([1,2,np.nan])
serie1

0    1.0
1    2.0
2    NaN
dtype: float64

In [18]:
serie2 = pd.Series([4,5,6])
serie2

0    4
1    5
2    6
dtype: int64

In [20]:
serie3 = serie1.combine_first(serie2) #completa los nan de serie1 con los valores de serie2
serie3

0    1.0
1    2.0
2    6.0
dtype: float64

In [21]:
#Ahora con DataFrames

In [22]:
valores = [1,2,np.nan]
dataframe1 = pd.DataFrame(valores)
dataframe1

0
0  1.0
1  2.0
2  NaN

In [23]:
valores2 = [4,5,6]
dataframe2 = pd.DataFrame(valores2)
dataframe2

0
0  4
1  5
2  6

In [24]:
#Creamos otro dataframe

In [26]:
dataframe3 = dataframe1.combine_first(dataframe2)
dataframe3

0
0  1.0
1  2.0
2  6.0