In [1]:
#Creando arrays

In [2]:
import numpy as np

In [3]:
np.zeros(4)

array([0., 0., 0., 0.])

In [4]:
np.ones(4)

array([1., 1., 1., 1.])

In [6]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [10]:
lista1 = [1,2,3,4]
array1 = np.array(lista1)

In [11]:
array1

array([1, 2, 3, 4])

In [12]:
lista2 = [5,6,7,8]
lista_doble = (lista1,lista2)

In [13]:
lista_doble

([1, 2, 3, 4], [5, 6, 7, 8])

In [15]:
array_doble = np.array(lista_doble)
array_doble

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [16]:
array_doble.shape #dimensiones del array

(2, 4)

In [17]:
array_doble.dtype #para saber el tipo de datos que contiene

dtype('int32')

In [18]:
#Operaciones con arrays

In [19]:
a1 = np.array([1,2,3,4])
a1

array([1, 2, 3, 4])

In [20]:
array1*2

array([2, 4, 6, 8])

In [21]:
array1+2

array([3, 4, 5, 6])

In [22]:
l1 = [1,2,3,4]
l2 = [5,6,7,8]
lista_doble = (l1,l2)
array_doble = np.array(lista_doble)
array_doble

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
array_doble + 10

array([[11, 12, 13, 14],
       [15, 16, 17, 18]])

In [24]:
array_doble**2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]], dtype=int32)

In [25]:
#indexacion con arrays

In [26]:
array = np.arange(0,11)
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
array[0:3]  #subconjunto

array([0, 1, 2])

In [29]:
array[3:8]

array([3, 4, 5, 6, 7])

In [30]:
array[:6]

array([0, 1, 2, 3, 4, 5])

In [36]:
array[6]

6

In [37]:
array_copia = array.copy()

In [38]:
array_copia

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
array_copia[0:3] = array_copia[0:3] ** 3

In [40]:
array_copia

array([ 0,  1,  8,  3,  4,  5,  6,  7,  8,  9, 10])

In [41]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
#Multidimensionales

In [44]:
array= np.array([[1,2,3],[3,4,5],[5,6,7]])

In [45]:
array

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [46]:
array[0]

array([1, 2, 3])

In [47]:
array.shape

(3, 3)

In [49]:
array[1][2]

5

In [50]:
#Transpuestas

In [51]:
A2 = np.arange(15).reshape((3,5))
A2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [53]:
A2[1][1]

6

In [56]:
A2_t = A2.T

In [57]:
A2_t

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [58]:
#Entrada y salida de arrays

In [60]:
array= np.arange(6)
array

array([0, 1, 2, 3, 4, 5])

In [61]:
#SALVAR un array para usarlo posteriormente

In [62]:
np.save('array_salvado_array',array)

In [63]:
np.load('array_salvado_array.npy')

array([0, 1, 2, 3, 4, 5])

In [64]:
#salvar en una misma variable 2 arrays

In [67]:
array_1= np.arange(6)
array_1
array_2= np.arange(2,7)
array_2

array([2, 3, 4, 5, 6])

In [68]:
np.savez('array_doble', x=array_1,y=array_2)

In [69]:
array_recuperado = np.load('array_doble.npz')

In [70]:
array_recuperado['x']

array([0, 1, 2, 3, 4, 5])

In [71]:
array_recuperado['y']

array([2, 3, 4, 5, 6])

In [72]:
#Salvar en un fichero de texto

In [75]:
np.savetxt('miArchivo.txt',array_1,delimiter="*")

In [77]:
np.loadtxt('miArchivo.txt',delimiter="*")

array([0., 1., 2., 3., 4., 5.])

In [78]:
#Funciones en arrays

In [79]:
array= np.arange(5)

In [80]:
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ])

In [81]:
np.random.rand(5)

array([0.25793541, 0.1189183 , 0.80529911, 0.33318731, 0.75456514])

In [85]:
lista = [5,4,6,8, 12]
array2 = np.array(lista)

In [86]:
array2

array([ 5,  4,  6,  8, 12])

In [87]:
array

array([0, 1, 2, 3, 4])

In [88]:
np.add(array, array2)

array([ 5,  5,  8, 11, 16])